name: Test deployment

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.devcontainer/**'
      - "**/.github/workflows/**"
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:   

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install 
      - name: Test build website
        env:
          UMAMI_WEBSITE_ID: ${{ vars.UMAMI_WEBSITE_ID }}
          UMAMI_ANALYTICS_DOMAIN: ${{ vars.UMAMI_ANALYTICS_DOMAIN }}
          UMAMI_DATAHOST_URL: ${{ vars.UMAMI_DATAHOST_URL }}
          UMAMI_DATA_DOMAIN: ${{ vars.UMAMI_DATA_DOMAINS }}
          UMAMI_DATA_TAG: ${{ vars.UMAMI_DATA_TAG }}
        run: npm run build